apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealedsecret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sealedsecret
  template:
    metadata:
      labels:
        app: sealedsecret
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
